### ISSUE TITLE
threads.c:(.text+0x165): undefined reference to `pthread_create'

### ISSUE THREAD

**Issue by francesco1119** [remzi-arpacidusseau/ostep-code#18]
I've recently download this repository and if I run `gcc -o threads threads.c -Wall` I receive this error: 

```
/usr/bin/ld: /tmp/ccJOGU9O.o: in function `main':
threads.c:(.text+0x165): undefined reference to `pthread_create'
/usr/bin/ld: threads.c:(.text+0x1a5): undefined reference to `pthread_create'
/usr/bin/ld: threads.c:(.text+0x1d9): undefined reference to `pthread_join'
/usr/bin/ld: threads.c:(.text+0x20d): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
```

I'm running `gcc (Debian 8.3.0-6) 8.3.0` on WSL2 on a `Microsoft Windows [Version 10.0.19042.1415]`

The code of threads.c is the one you have in the repository, I haven't touched it

**Comment by pkivolowitz** [comment]
-lpthread

need the library in the link.

**Comment by xp4ns3** [comment]
On Wed, 22 Dec 2021, 23:43 Francesco Mantovani, ***@***.***>
wrote:

> I've recently download this repository and if I run gcc -o threads
> threads.c -Wall I receive this error:
>
> /usr/bin/ld: /tmp/ccJOGU9O.o: in function `main':
> threads.c:(.text+0x165): undefined reference to `pthread_create'
> /usr/bin/ld: threads.c:(.text+0x1a5): undefined reference to `pthread_create'
> /usr/bin/ld: threads.c:(.text+0x1d9): undefined reference to `pthread_join'
> /usr/bin/ld: threads.c:(.text+0x20d): undefined reference to `pthread_join'
> collect2: error: ld returned 1 exit status
>
> I'm running gcc (Debian 8.3.0-6) 8.3.0 on WSL2 on a Microsoft Windows
> [Version 10.0.19042.1415]
>
> The code of threads.c is the one you have in the repository, I haven't
> touched it
>

I know nothing about WSL2 on Windows. However, on Linux, programs that use
the Pthreads API should be compiled using the GCC toolchain with the
"-pthread" option.

The linker (/usr/bin/ld) is complaining about not being able to resolve
symbols of Pthreads API (pthread_create(), pthread_join()), i.e. it cannot
find the definition of those functions.

Please try the following variation to the command you are using...

"gcc -o threads threads.c -pthread -Wall".

For further information you may refer to "man 7 pthreads".

Regards,

Fabio M. De Francesco

**Comment by francesco1119** [comment]
Oh, yeah, @xp4ns3 , it worked:

![image](https://user-images.githubusercontent.com/3397477/147921412-b3624d28-17fe-4328-857d-ff19b0f4a5e4.png)
